# Comment
print('Hello World')
print('What is your name?')
myName = input()
print('Hello ' + myName)
print('The length of your name is ' )
print( (len(myName))j)
print('what is your age?')
myAge = input()
print('you will be '+ str(int(myAge) + 1) + ' in a year.')